### ISSUE TITLE
Программа вылетает при нажатии на кнопку "генерировать"

### ISSUE THREAD

**Issue by ChupakabraMSK** [qiwichupa/RussianFIO2AD#3]
Отличная идея - но Программа вылетает при нажатии на кнопку "генерировать"

Вин10

**Comment by ChupakabraMSK** [comment]
на предыдущем релизе то же вылетает/
причем если я копирую в буфер обмена одну ячейку из таблицы экселя или онлиофиса то все ок
а если я ы буфер обмена копирую 89 строк с фио из экселя - вылетает при нажатии на кнопку

**Comment by ChupakabraMSK** [comment]
9 строк - все ок

**Comment by qiwichupa** [comment]
по идее количество не должно приводить к вылету, скорее всего какое-то конкретное фио не может корректно воткнуться по какой-то причине.

**Comment by ChupakabraMSK** [comment]
> по идее количество не должно приводить к вылету, скорее всего какое-то конкретное фио не может корректно воткнуться по какой-то причине.

Да, отловил, прога вылетает там где нет Отчества

**Comment by qiwichupa** [comment]
Да, не дело крашиться по таким пустякам, воткнул обработку такой ситуации - теперь будет писать в лог и подсвечивать нестандартное ФИО при генерации.

[https://github.com/qiwichupa/RussianFIO2AD/releases/tag/v.0.1.1](https://github.com/qiwichupa/RussianFIO2AD/releases/tag/v.0.1.1)

**Comment by ChupakabraMSK** [comment]
Теперь все ок при генерации и создании учеток
