### ISSUE TITLE
к какому контроллеру АД подключается программа?

### ISSUE THREAD

**Issue by ChupakabraMSK** [qiwichupa/RussianFIO2AD#5]
Хотелось бы видеть к какому контроллеру АД подключилась программа

А в идеале - иметь возможность выбора DC

**Comment by qiwichupa** [comment]
Подумаю можно ли что-то такое сделать... Насколько я помню, модуль работы с AD имеет ряд ограничений, в частности мне так и не удалось реализовать подключение к контроллеру с компа не-члена домена. Но как минимум показать имя контроллера, думаю, должно получиться. Вообще насколько я понял, в качестве контроллера выбирается тот, на котором авторизовался хост (но это не точно)

**Comment by qiwichupa** [comment]
Вдумчиво почитал доки к модулю и не обнаружил, увы, способа выяснить к какому точно контроллеру идут обращения =\
