### ISSUE TITLE
Не хватает кнопки "очистить" или "сбросить"

### ISSUE THREAD

**Issue by ChupakabraMSK** [qiwichupa/RussianFIO2AD#6]
Что бы сбросить список скопированных и сгенеренных пользаков

**Comment by qiwichupa** [comment]
а зачем? При генерации список обнуляется и заполняется по новой в соответствии со списком ФИО. Кнопку сброса не то чтобы сложно сделать, но вроде бы и не за чем, и интерфейс загромождать не хочется (и так кнопок слишком много, вместо одной "сделать хорошо")
