### ISSUE TITLE
Ошибка: The requested object does not exist.(Абдулов Садридин: Abdulov_S) 

### ISSUE THREAD

**Issue by ChupakabraMSK** [qiwichupa/RussianFIO2AD#7]
при создании учеток выдает иногда такую ошибку

Ошибка: The requested object does not exist.(Абдулов Садридин: Abdulov_S) 

причем при повторном запуске создается норм

Создана учетная запись "Абдулов Садридин": 1122qqAA, <ADContainer 'OU=HML,OU=Склад IDL УЗ пользователей WMS,OU=Technical accounts,DC=sands,DC=local'>

**Comment by qiwichupa** [comment]
Внес пару изменений, которые должны уменьшить вероятность ошибки при создании учеток. Не 100%, потому что фиг знает откуда они берутся. Я предположил, что скорее всего из-за интенсивности операций, поэтому добавил микрозадержки. На тестовом домене полторы сотни учеток создал - всё ок.

[https://github.com/qiwichupa/RussianFIO2AD/releases/tag/v.0.1.2](https://github.com/qiwichupa/RussianFIO2AD/releases/tag/v.0.1.2)

**Comment by qiwichupa** [comment]
Половил эту ошибку - понял что нифига не понял откуда она берется, но поставил костыль, который вроде как позволяет ее избежать.
[https://github.com/qiwichupa/RussianFIO2AD/releases/tag/v0.1.3](https://github.com/qiwichupa/RussianFIO2AD/releases/tag/v0.1.3)
